# Build: sudo docker build -t <project_name> .
# Run: sudo docker run -v $(pwd):/workspace/project --gpus all -it --rm <project_name>


FROM  nvidia/cuda:11.0.3-base-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive

RUN rm /etc/apt/sources.list.d/cuda.list
RUN apt-key del 7fa2af80
RUN apt-get update && apt-get install -y --no-install-recommends wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb


EXPOSE 8501

# Basic setup
RUN apt update && apt install -y bash \
                   build-essential \
                   git \
                   curl \
                   ca-certificates \
                   wget \
                   && rm -rf /var/lib/apt/lists

# Set working directory
WORKDIR /workspace/project


# Install Miniconda and create main env
ADD https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh miniconda3.sh
RUN /bin/bash miniconda3.sh -b -p /conda \
    && echo export PATH=/conda/bin:$PATH >> .bashrc \
    && rm miniconda3.sh
ENV PATH="/conda/bin:${PATH}"
RUN conda create --name diffusers python=3.10


# Switch to bash shell
SHELL ["/bin/bash", "-c"]


# Install requirements
COPY ./src ./src
COPY ./config.yaml ./config.yaml
COPY ./models ./models
COPY ./requirements_backend.txt ./
RUN source activate diffusers \
    && pip install --no-cache-dir -r requirements_backend.txt && PYTHONPATH=. python src/app/init_backend.py

ENTRYPOINT cd /workspace/project/ && source activate diffusers && PYTHONPATH=. python src/app/backend.py
